name: Auto Image Rebuild
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:

  build-alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Alpine Docker Image
        uses: docker/build-push-action@v2.6.1
        with:
          context: "${{ github.workspace }}"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/caddy-cloudflare:2.6.1-builder-alpine
          file: "Dockerfile.alpine"
